##Linear Array

In [2]:
import numpy as np

In [2]:
##reverse out of place
def reverseArrayOutOfPlace(arr):
  revArr=[None] * len(arr) # create an array of None values of same length as arr
  i=0 
  j=len(arr)-1 # j is the last index of arr
  while i < len(arr): # 
    revArr[i] =arr[j] 
    i+=1
    j-=1
  return np.array(revArr)
a=reverseArrayOutOfPlace(np.array([1,2,3,4,6,5,4,8,5]))


print(a)

[5 8 4 5 6 4 3 2 1]


In [4]:
def reverseArrayOutOfPlace(arr):
    reversed=[0]*len(arr)
    for i in range(len(arr)):# using for loop to iterate through the array
        reversed[i]=arr[len(arr)-1-i]

    return np.array(reversed)


a=reverseArrayOutOfPlace(np.array([1,2,3,4,6,5,4,8,5]))


print(a)

[5 8 4 5 6 4 3 2 1]


In [4]:
## in place reverse
def inplace_reverse(arr):
  i=0
  j=len(arr)-1
  while i < len(arr):
    arr[i] = arr[j]
    i+=1
    j-=1
  return arr
a=inplace_reverse(np.array([1,2,3,4,6,5,4,8,5]))
print(a)

[5 8 4 5 6 5 4 8 5]


In [ ]:
#left shift
def leftShift(arr):
  i=0
  while i<len(arr)-1:
    arr[i]=arr[i+1]
    i+=1
  arr[len(arr)-1]=None
  return arr
A=leftShift([1,2,5,48,6,5,3,5,6,2,5,3,2,5,3,5,3,5,3])
B=leftShift(A)
print(A)



In [ ]:
#right shift
def rightShift(arr):
  i=len(arr)-1
  while i > 0:
    arr[i]=arr[i-1]
    i-=1

  arr[0]=None
  return arr
A=rightShift([1,2,5,48,6,5,3,5,6,2,5,3,2,5,3,5,3,5,3])
print(A)

In [1]:
#rotate left
def rotateLeft(arr):
  temp=arr[0]
  i=0
  while i<len(arr)-1:
    arr[i]=arr[i+1]
    i+=1
  arr[len(arr)-1]=temp
  return arr
A=rotateLeft([1,2,5,48,6,5,3,5,6,2,5,3,2,5,3,5,3,5,3])
print(A)

[2, 5, 48, 6, 5, 3, 5, 6, 2, 5, 3, 2, 5, 3, 5, 3, 5, 3, 1]


In [ ]:
#rotate right
def rotateRight(arr):
  temp=arr[len(arr)-1]
  i=len(arr)-1
  while i > 0:
    arr[i]=arr[i-1]
    i-=1
  arr[0]=temp
  return arr
A=rotateRight([1,2,5,48,6,5,3,5,6,2,5,3,2,5,3,5,3,5,3])
print(A)

##Multidimensional Array

In [ ]:
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

In [ ]:
import numpy as np
#2D Array
def createArray():
  m=np.zeros((2,3), dtype=int)
  for i in range(2):
    for j in range(3):
      print(f'element of [{i}][{j}] index:' )
      m[i][j]=int(input())
  return m
print_matrix(createArray())

In [ ]:
#row wise iteration
def print_row(m):
  row,col = m.shape
  for i in range(row):
    for j in range(col):
      print(m[i][j],end=" ")
    print()
m=np.array([[4,3,8],[2,5,1]])
print_matrix(m)
print_row(m)

In [ ]:
#column wise iteration
def column_print(m):
  row , col = m.shape
  for i in range(col):
    for j in range(row):
      print(m[j][i],end=" ")
    print()
column_print(m)


In [ ]:
#row wise sum
def row_wise_sum(m):
  row , col = m.shape
  result = np.zeros((row,1),dtype=int)
  for i in range(row):
    for j in range(col):
      result[i][0]+=m[i][j]
  return result
m=row_wise_sum(m)
print_matrix(m)

In [ ]:
#col wise sum
def col_wise_sum(m):
  row , col = m.shape
  result=np.zeros((1,col),dtype=int)
  for i in range(row):
    for j in range(col):
      result[0][j]+=m[i][j]
  return result
m=np.array([[4,3,8],[2,5,1]])

print_matrix(col_wise_sum(m))