In [1]:
#reverse Out of place
import numpy as np

arra=np.array([1,2,3,4,5])
#Target       [5,4,3,2,1]
# cant use reverse indexing and cant use any functions

def reverseOutOfPlace(arr):
    reversedArray=np.zeros(len(arr),dtype=int)
    # reversedArray= [None]*len(arr)

    i=0
    j=len(arr)-1

    while i<len(arr):

        reversedArray[i]=arr[j]

        i+=1
        j-=1

    return reversedArray

kk=np.array([1,2,3,4,5])
print(reverseOutOfPlace(kk))

    


[5 4 3 2 1]


In [2]:
#Left Shift
import numpy as np

a=np.array([1,2,3,4,5])
#          [2 3 4 5 0]
def leftShift(arr):
    for i in range(1,len(arr)-1):

        arr[i-1]=arr[i]

    arr[len(arr)-1]=0
    return arr


a=np.array([1,2,3,4,5])

a=leftShift(a)
print(a)

[2 3 4 4 0]


In [14]:
#Right Shift
import numpy as np

a=np.array([1,2,3,4,5])
#          [0 1 2 3 4]
def rightShift(arr):
    for i in range(len(arr)-1,0,-1):

        arr[i]=arr[i-1]

    arr[0]=0
    return arr

a=np.array([1,2,3,4,5])

a=rightShift(a)
print(a)

[0 1 2 3 4]
