In [2]:
#Importing library
import numpy as np

In [ ]:
#Initializing lists

a = [1, 2, 3, 4, 5]
print(a)
print(type(a))

In [ ]:
a = [1, 2.0, "a", 3]
print(a) #storing different datatypes is also possible in list

In [ ]:
#Initializing a numpy array using a list

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

In [ ]:
#Initializing a numpy array using a zeros

a = np.zeros(3)
print(a) #datatype by default is float

In [ ]:
a = np.zeros(3, dtype = int)
print(a) #dataype will be int

In [ ]:
#Initializing a numpy using None

a = np.array([None]*5)
print(a) #in this method, you can initialize a numpy array with any values

In [ ]:
a = np.array([1, 2.0, 3])
print(a) #check the datatype of printed array

In [ ]:
a = np.array([1, "2", 3])
print(a) #check the datatype of printed array

In [ ]:
#Accessing array through index
a = np.array([1, 2, 3, 4, 5])
print(a[2])

a[2] = 6 #a[2] will be updated from 3 to 6
print(a)

In [ ]:
#Finding length of array
print(len(a))
print(a.shape)
print(a.shape[0])

In [ ]:
#Iterating through array
for i in a:
  print(i) #regular for loop, checks membership

In [ ]:
for i in range(len(a)):
  print(a[i]) #ranged for loop, iterates through the index

In [ ]:
#resizing an array
a = np.array([1, 2, 3, 4, 5, 6])

b = np.array([None]*8) #initializing a new array with length 8 and all None values
for i in range(len(a)):
  b[i] = a[i]
print(b)

In [ ]:
#copying an array (pass by reference)

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1
print(arr2)

In [ ]:
print(id(arr1)) #prints the memory location of arr1
print(id(arr2)) #prints the memory location of arr2

In [ ]:
arr2 = np.zeros(len(arr1))

for i in range(arr1[i]):
  arr2[i] = arr1[i]

print(arr2)

In [8]:
#shifting array left
import numpy as np
def shiftLeft(a):
  for i in range(1, len(a)):
    a[i-1] = a[i]
    print("for i = ", i, "array = ", a)
  a[len(a)-1] = 0
  return a

a = np.array([1, 2, 3, 4])
print(a)

print(f"After left shifting, array a will look like: {shiftLeft(a)}")

[1 2 3 4]
for i =  1 array =  [2 2 3 4]
for i =  2 array =  [2 3 3 4]
for i =  3 array =  [2 3 4 4]
After left shifting, array a will look like: [2 3 4 0]


In [9]:
#shifting array right

def shiftRight(a):
  for i in range(len(a)-1,0,-1):
    a[i]=a[i-1]
    print("for i = ", i, "array = ", a)
  a[0]=0
  return a

a = np.array([1, 2, 3, 4])
print(a)
print(f"After right shifting, array a will look like: {shiftRight(a)}")

[1 2 3 4]
for i =  3 array =  [1 2 3 3]
for i =  2 array =  [1 2 2 3]
for i =  1 array =  [1 1 2 3]
After right shifting, array a will look like: [0 1 2 3]


In [4]:
#rotating array left

def rotateLeft(a):
  temp=a[0]
  for i in range(1,len(a)):
    a[i-1]=a[i]
  a[len(a)-1]=temp
  return a

a = np.array([1, 2, 3, 4])
print(a)
print(f"After left rotating, array a will look like: {rotateLeft(a)}")

[1 2 3 4]
After left rotating, array a will look like: [2 3 4 1]


In [12]:
#rotate array right (wrong code)

def rotateRight(a):
  temp=a[len(a)-1]
  for i in range(1,len(a)):
    a[i]=a[i-1]
    print("for i = ", i, "array = ", a)
  a[0]=temp
  return a


a = np.array([1, 2, 3, 4])
print(a)
print(f"After wrong for loop right rotating, array a will look like: {rotateRight(a)}")

[1 2 3 4]
for i =  1 array =  [1 1 3 4]
for i =  2 array =  [1 1 1 4]
for i =  3 array =  [1 1 1 1]
After wrong for loop right rotating, array a will look like: [4 1 1 1]


In [14]:
#rotate array right (correct code)
def rotateRight(a):
  temp=a[len(a)-1]
  for i in range(len(a)-1,0,-1):
    a[i]=a[i-1]
    print("for i = ", i, "array = ", a)
  a[0]=temp
  return a


a = np.array([1, 2, 3, 4])
print(a)
print(f"After right rotating, array a will look like: {rotateRight(a)}")

[1 2 3 4]
for i =  3 array =  [1 2 3 3]
for i =  2 array =  [1 2 2 3]
for i =  1 array =  [1 1 2 3]
After right rotating, array a will look like: [4 1 2 3]


In [6]:
#insertion at end

def insertAtEnd(arr, size, elem):
  if size >= len(arr):
    return "Need to resize"
  arr[size] = elem
  return arr

a = np.array([1, 2, 3, 4, 5, 0, 0])
print(insertAtEnd(a, 5, 9))

[1 2 3 4 5 9 0]


In [16]:
#insertion at any other place
import numpy as np
def insertAtOtherPlace(arr, size, elem, index):
  """
  Inserts an element at a specified index in the array.
  Parameters:
  arr (list): The array in which the element is to be inserted.
  size (int): The current number of elements in the array.
  elem (any): The element to be inserted.
  index (int): The position at which the element is to be inserted.
  Returns:
  list: The array with the element inserted if successful.
  str: An error message if the insertion is not possible or resizing is needed.
  Notes:
  - If the index is out of bounds (less than 0 or greater than size), the function returns "Insertion not possible".
  - If the array is full (size is greater than or equal to the length of the array), the function returns "Need to resize".
  - The function shifts elements to the right to make space for the new element.
  """
  if index < 0 or index > size:
    return "Insertion not possible"
  if size >= len(arr):
    return "Need to resize"
  

  for i in range(size, index, -1):
    arr[i] = arr[i-1]
  arr[index] = elem
  return arr
a = np.array([1, 2, 3, 4, 5, 0, 0])
print(a,"before")
print(insertAtOtherPlace(a, 5, 9, 3))

[1 2 3 4 5 0 0] before
[1 2 3 9 4 5 0]


In [ ]:
#deletion at end

def deleteAtEnd(arr, size):
  if size<=0:
    return "Deletion not possible"
  else:
    arr[size-1]=0
  return arr

a = np.array([1, 2, 3, 4, 5])
print(deleteAtEnd(a, 5))

[1 2 3 4 0]


In [22]:
#delete at any place
import numpy as np
def deleteAtOtherPlace(arr, size, index):
    if size<=0:
        return "Deletion not possible"
    if index < 0 or index >= size:
        return "Deletion not possible"
    for i in range(index+1, size):
        arr[i-1] = arr[i]
    arr[size-1] = 0
    return arr

a = np.array([1, 2, 3, 4, 5])
print(a, "before")

print("after",deleteAtOtherPlace(a, 5, 2))

[1 2 3 4 5] before
after [1 2 4 5 0]


In [ ]:
#linear searching

def linearSearch(arr, size, key):
  found = False
  for i in range(size):
    if arr[i] == key:
      found = True
      break
  if found == True:
    return 'Element Found!'
  else:
    return 'Not found :('

a = np.array([5, 6, 13, 2, 9])
print(linearSearch(a, 5, 13))
print(linearSearch(a, 5, 23))

In [33]:
#binary searching

def binarySearch(arr, key):
  low = 0
  high = len(arr)-1
  while low <= high:
    mid = (low + high)//2




    if arr[mid] == key:
      return f'Element Found! idx: {mid}'
    
    elif arr[mid] < key:

      low = mid + 1


    elif arr[mid] > key:

      high = mid - 1


  return 'Not found :('

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11])
print(binarySearch(a, 8))


Element Found! idx: 7


In [ ]:
#array reversal  with while loop

def reverseArrayInPlace(arr):
  i = 0
  j = len(arr)-1
  
  while i < j:
    arr[i], arr[j] = arr[j], arr[i]
    
    i += 1
    j -= 1
  return arr


a = np.array([5, 6, 13, 2, 9])
print(reverseArrayInPlace(a))

[ 9  2 13  6  5]


In [ ]:
#array reversal in place with for loop
def reverseArrayInPlace(arr):
  n = len(arr)
  for i in range(n // 2):
    arr[i], arr[n - i - 1] = arr[n - i - 1], arr[i]
  return arr


a = np.array([5, 6, 13, 2, 9])
print(reverseArrayInPlace(a))

In [ ]:
#
"""
This script initializes an array `arr` with integer values and creates a new array `new_arr` of zeros with a length of 10.
It then copies the elements of `arr` into `new_arr`, placing each element at every second position, starting from the first position.
Variables:
    arr (numpy.ndarray): An array of integers with values [10, 20, 30, 40, 50].
    new_arr (numpy.ndarray): An array of zeros with a length of 10.
    j (int): An index variable used to place elements in `new_arr`.
Process:
    - Iterate over each element in `arr`.
    - Assign the current element of `arr` to the `j`-th position of `new_arr`.
    - Increment `j` by 2 to place the next element at every second position.
Output:
    Prints the `new_arr` array after copying elements from `arr`.
"""

arr=np.array([10,20,30,40,50], dtype=int)
new_arr=np.zeros(10,dtype=int)
j=0
for i in range(len(arr)):
    
    new_arr[j]=arr[i] 
    j+=2


print(new_arr)

[10  0 20  0 30  0 40  0 50  0]


In [ ]:
#Union OF two array
import numpy as np
def union_two(a,b):
    result=np.zeros(len(a)+len(b),dtype=int)
    res_idx=0


    for i in range(len(a)):
        is_unique=True
        for j in range(res_idx):
            if result[j]==a[i]:
                is_unique=False
                break
        if is_unique:
            result[res_idx]=a[i]
            res_idx+=1

    for i in range(len(b)):
        is_unique=True
        for j in range(res_idx):
            if result[j]==b[i]:
                is_unique=False
                break
        if is_unique:
            result[res_idx]=b[i]
            res_idx+=1

    return result[:res_idx]

a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

print(union_two(a,b))
#

[1 2 3 4 5 6 7 8]


In [7]:
# transfer negative elements to the end of the array
import numpy as np


def negToLast(arr):
    result = np.zeros(len(arr), dtype=int)

    pos_idx=0
    neg_idx=len(arr)-1

    for i in range(len(arr)):
        if arr[i]>=0:
            result[pos_idx]=arr[i]
            pos_idx+=1
        else:
            result[neg_idx]=arr[i]
            neg_idx-=1

    return result

arr=np.array([1,-2,3,-4,5,-6,7,-8,9])
print(negToLast(arr))


[ 1  3  5  7  9 -8 -6 -4 -2]


In [1]:
import numpy as np

# Function to print the matrix in a readable format
def print_matrix(seat_status):
    for row in seat_status:
        print(' '.join(row))

# Function to rotate the seating rows based on the exam week
def row_rotation(exam_week, seat_status):
    # Number of rows
    num_rows = len(seat_status)
    
    # Calculate the new starting row after the exam week
    shift = exam_week - 1  # Shift rows based on exam week (Week 1 -> shift = 0)
    rotated_seat_status = np.roll(seat_status, shift, axis=0)  # Roll rows up
    
    # Print the rotated seating arrangement
    print_matrix(rotated_seat_status)
    print()
    
    # Find the row where "AA" will be seated
    for i, row in enumerate(rotated_seat_status):
        if 'AA' in row:
            return i + 1  # Return the row number (1-based index)

# Example seat status array
seat_status = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['F', 'G', 'H', 'I', 'J'],
    ['K', 'L', 'M', 'N', 'O'],
    ['P', 'Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X', 'Y'],
    ['Z', 'AA', 'BB', 'CC', 'DD']
])

# Exam week input
exam_week = 3

# Print the current seating arrangement
print("Current seating arrangement:")
print_matrix(seat_status)
print()

# Call the row_rotation function to get the updated row
row_number = row_rotation(exam_week, seat_status)

# Print the row where "AA" will be seated
print(f'Your friend AA will be on row {row_number}')


Current seating arrangement:
A B C D E
F G H I J
K L M N O
P Q R S T
U V W X Y
Z AA BB CC DD

U V W X Y
Z AA BB CC DD
A B C D E
F G H I J
K L M N O
P Q R S T

Your friend AA will be on row 2
