In [1]:
#Importing library
import numpy as np

In [ ]:
#Initializing lists

a = [1, 2, 3, 4, 5]
print(a)
print(type(a))

In [ ]:
a = [1, 2.0, "a", 3]
print(a) #storing different datatypes is also possible in list

In [ ]:
#Initializing a numpy array using a list

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

In [ ]:
#Initializing a numpy array using a zeros

a = np.zeros(3)
print(a) #datatype by default is float

In [ ]:
a = np.zeros(3, dtype = int)
print(a) #dataype will be int

In [ ]:
#Initializing a numpy using None

a = np.array([None]*5)
print(a) #in this method, you can initialize a numpy array with any values

In [ ]:
a = np.array([1, 2.0, 3])
print(a) #check the datatype of printed array

In [ ]:
a = np.array([1, "2", 3])
print(a) #check the datatype of printed array

In [ ]:
#Accessing array through index
a = np.array([1, 2, 3, 4, 5])
print(a[2])

a[2] = 6 #a[2] will be updated from 3 to 6
print(a)

In [ ]:
#Finding length of array
print(len(a))
print(a.shape)
print(a.shape[0])

In [ ]:
#Iterating through array
for i in a:
  print(i) #regular for loop, checks membership

In [ ]:
for i in range(len(a)):
  print(a[i]) #ranged for loop, iterates through the index

In [ ]:
#resizing an array
a = np.array([1, 2, 3, 4, 5, 6])

b = np.array([None]*8) #initializing a new array with length 8 and all None values
for i in range(len(a)):
  b[i] = a[i]
print(b)

In [ ]:
#copying an array (pass by reference)

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1
print(arr2)

In [ ]:
print(id(arr1)) #prints the memory location of arr1
print(id(arr2)) #prints the memory location of arr2

In [ ]:
arr2 = np.zeros(len(arr1))

for i in range(arr1[i]):
  arr2[i] = arr1[i]

print(arr2)

In [8]:
#shifting array left
import numpy as np
def shiftLeft(a):
  for i in range(1, len(a)):
    a[i-1] = a[i]
    print("for i = ", i, "array = ", a)
  a[len(a)-1] = 0
  return a

a = np.array([1, 2, 3, 4])
print(a)

print(f"After left shifting, array a will look like: {shiftLeft(a)}")

[1 2 3 4]
for i =  1 array =  [2 2 3 4]
for i =  2 array =  [2 3 3 4]
for i =  3 array =  [2 3 4 4]
After left shifting, array a will look like: [2 3 4 0]


In [9]:
#shifting array right

def shiftRight(a):
  for i in range(len(a)-1,0,-1):
    a[i]=a[i-1]
    print("for i = ", i, "array = ", a)
  a[0]=0
  return a

a = np.array([1, 2, 3, 4])
print(a)
print(f"After right shifting, array a will look like: {shiftRight(a)}")

[1 2 3 4]
for i =  3 array =  [1 2 3 3]
for i =  2 array =  [1 2 2 3]
for i =  1 array =  [1 1 2 3]
After right shifting, array a will look like: [0 1 2 3]


In [4]:
#rotating array left

def rotateLeft(a):
  temp=a[0]
  for i in range(1,len(a)):
    a[i-1]=a[i]
  a[len(a)-1]=temp
  return a

a = np.array([1, 2, 3, 4])
print(a)
print(f"After left rotating, array a will look like: {rotateLeft(a)}")

[1 2 3 4]
After left rotating, array a will look like: [2 3 4 1]


In [5]:
#rotate array right

def rotateRight(a):
  temp=a[len(a)-1]
  for i in range(len(a)-1,0,-1):
    a[i]=a[i-1]
  a[0]=temp
  return a


a = np.array([1, 2, 3, 4])
print(a)
print(f"After right rotating, array a will look like: {rotateRight(a)}")

[1 2 3 4]
After right rotating, array a will look like: [4 1 2 3]


In [6]:
#insertion at end

def insertAtEnd(arr, size, elem):
  if size >= len(arr):
    return "Need to resize"
  arr[size] = elem
  return arr

a = np.array([1, 2, 3, 4, 5, 0, 0])
print(insertAtEnd(a, 5, 9))

[1 2 3 4 5 9 0]


In [63]:
#insertion at any other place
import numpy as np
def insertAtOtherPlace(arr, size, elem, index):
  if index < 0 or index > size:
    return "Insertion not possible"
  if size >= len(arr):
    return "Need to resize"
  for i in range(size, index, -1):
    arr[i] = arr[i-1]
  arr[index] = elem
  return arr
a = np.array([1, 2, 3, 4, 5, 0, 0])
print(insertAtOtherPlace(a, 5, 9, 3))

[1 2 3 9 4 5 0]


In [ ]:
#deletion at end

def deleteAtEnd(arr, size):
  if size<=0:
    return "Deletion not possible"
  else:
    arr[size-1]=0
  return arr

a = np.array([1, 2, 3, 4, 5])
print(deleteAtEnd(a, 5))

[1 2 3 4 0]


In [62]:
#delete at any place
import numpy as np
def deleteAtOtherPlace(arr, size, index):
    if size<=0:
        return "Deletion not possible"
    if index < 0 or index >= size:
        return "Deletion not possible"
    for i in range(index, size-1):
        arr[i] = arr[i+1]
    arr[size-1] = 0
    return arr

a = np.array([1, 2, 3, 4, 5])
print(deleteAtOtherPlace(a, 5, 2))

[1 2 4 5 0]


In [ ]:
#linear searching

def linearSearch(arr, size, key):
  found = False
  for i in range(size):
    if arr[i] == key:
      found = True
      break
  if found == True:
    return 'Element Found!'
  else:
    return 'Not found :('

a = np.array([5, 6, 13, 2, 9])
print(linearSearch(a, 5, 13))
print(linearSearch(a, 5, 23))

In [ ]:
#binary searching

def binarySearch(arr, key):
  low = 0
  high = len(arr)-1
  while low <= high:
    mid = (low + high)//2


    print("mid = ", mid)


    if arr[mid] == key:
      return 'Element Found!'
    
    elif arr[mid] < key:

      low = mid + 1


      print("low = ", low)
    else:

      high = mid - 1


      print("high = ", high)
  return 'Not found :('

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11])
print(binarySearch(a, 8))
print(binarySearch(a, 3))

mid =  5
low =  6
mid =  8
high =  7
mid =  6
low =  7
mid =  7
Element Found!
mid =  5
high =  4
mid =  2
Element Found!


In [105]:
#array reversal

def reverseArrayInPlace(arr):
  start = 0
  
  end = len(arr)-1
  
  while start < end:
    arr[start], arr[end] = arr[end], arr[start]
    
    start += 1
    print("start = ", start)
    end -= 1
    print("end = ", end)
  return arr


a = np.array([5, 6, 13, 2, 9])
print(reverseArrayInPlace(a))

start =  1
end =  3
start =  2
end =  2
[ 9  2 13  6  5]


In [3]:
import numpy as np
arr=np.array([10,20,30,40,50], dtype=int)
new_arr=np.zeros(10,dtype=int)
j=0
for i in range(len(arr)):
    
    new_arr[j]=arr[i]
    j+=2


print(new_arr)

[10  0 20  0 30  0 40  0 50  0]


In [3]:
#Union OF two array
import numpy as np
def union_two(a,b):
    result=np.zeros(len(a)+len(b),dtype=int)
    res_idx=0


    for i in range(len(a)):
        is_unique=True
        for j in range(res_idx):
            if result[j]==a[i]:
                is_unique=False
                break
        if is_unique:
            result[res_idx]=a[i]
            res_idx+=1

    for i in range(len(b)):
        is_unique=True
        for j in range(res_idx):
            if result[j]==b[i]:
                is_unique=False
                break
        if is_unique:
            result[res_idx]=b[i]
            res_idx+=1

    return result[:res_idx]

a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

print(union_two(a,b))


[1 2 3 4 5 6 7 8]
